// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {requestdata} from '../models';
import {model} from '../models';

export function Create(arg1:requestdata.CreateTaskReq):Promise<model.Task>;

export function Delete(arg1:requestdata.DeleteTaskReq):Promise<void>;

export function GetAll():Promise<Array<model.Task>>;

export function Update(arg1:requestdata.UpdateTaskReq):Promise<model.Task>;
