// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {requestdata} from '../models';
import {model} from '../models';

export function Create(arg1:requestdata.CreateTagReq):Promise<model.Tag>;

export function Delete(arg1:requestdata.DeleteTagReq):Promise<void>;

export function GetAll():Promise<Array<model.Tag>>;

export function Update(arg1:requestdata.UpdateTagReq):Promise<model.Tag>;
