// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {requestdata} from '../models';
import {model} from '../models';

export function Create(arg1:requestdata.CreateUserReq):Promise<model.User>;

export function Delete(arg1:requestdata.DeleteUserReq):Promise<void>;

export function GetAll():Promise<Array<model.User>>;

export function Update(arg1:requestdata.UpdateUserReq):Promise<model.User>;
